export type Event = {
  id: number;
  organizerId: string;
  title: string;
  description?: string;
  categoryId?: number;
  subcategories?: string[];
  tags?: string[];
  eventType?: string;
  startDate: Date;
  endDate?: Date;
  location?: string;
  city?: string;
  isOutdoor?: boolean;
  capacity?: number;
  ticketPrice?: number;
  isPublic?: boolean;
  status?: 'draft' | 'published' | 'cancelled';
  multimedia?: any;
  createdAt?: Date;
  updatedAt?: Date;
};
