// src/screens/artist/PortalStyles.ts
import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },

  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f3e8ff', gap: 10 },
  closeBtn: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#faf5ff', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { flex: 1, fontSize: 17, fontFamily: 'PlusJakartaSans_700Bold', color: '#4c1d95' },
  availRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  availLabel: { fontSize: 11, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#9ca3af' },
  availOn: { color: '#7c3aed' },

  content: { paddingBottom: 24 },

  hero: { marginHorizontal: 16, marginTop: 16, borderRadius: 20, padding: 20, flexDirection: 'row', alignItems: 'center' },
  heroSup: { fontSize: 13, fontFamily: 'PlusJakartaSans_500Medium', color: 'rgba(255,255,255,0.85)', marginBottom: 4 },
  heroPct: { fontSize: 48, fontFamily: 'PlusJakartaSans_800ExtraBold', color: '#fff', lineHeight: 52 },
  heroMsg: { fontSize: 12, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(255,255,255,0.85)', marginTop: 6 },
  heroCircle: { width: 72, height: 72, borderRadius: 36, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  heroCirclePct: { fontSize: 20, fontFamily: 'PlusJakartaSans_800ExtraBold', color: '#fff' },
  heroCircleLbl: { fontSize: 9, fontFamily: 'PlusJakartaSans_500Medium', color: 'rgba(255,255,255,0.85)' },

  progressWrap: { marginHorizontal: 16, marginTop: 16 },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  progressLbl: { fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#4c1d95' },
  progressPts: { fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#9333ea' },
  progressBg: { height: 8, backgroundColor: '#e9d5ff', borderRadius: 4, overflow: 'hidden' },
  progressBar: { height: 8, borderRadius: 4 },

  bioEditor: { marginHorizontal: 16, marginTop: 16, backgroundColor: '#faf5ff', borderRadius: 16, padding: 16, borderWidth: 1.5, borderColor: '#e9d5ff' },
  bioEditorTitle: { fontSize: 14, fontFamily: 'PlusJakartaSans_700Bold', color: '#4c1d95', marginBottom: 10 },
  bioInput: { backgroundColor: '#fff', borderRadius: 12, padding: 12, fontSize: 14, fontFamily: 'PlusJakartaSans_400Regular', color: '#1e1b4b', minHeight: 100, borderWidth: 1, borderColor: 'rgba(124,58,237,0.2)', textAlignVertical: 'top' },
  bioActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  bioCancel: { flex: 1, paddingVertical: 12, borderRadius: 12, borderWidth: 1.5, borderColor: 'rgba(124,58,237,0.2)', alignItems: 'center' },
  bioCancelTxt: { fontSize: 14, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#7c3aed' },
  bioSave: { flex: 2, borderRadius: 12, overflow: 'hidden' },
  bioSaveGrad: { paddingVertical: 12, alignItems: 'center' },
  bioSaveTxt: { fontSize: 14, fontFamily: 'PlusJakartaSans_700Bold', color: '#fff' },

  section: { marginHorizontal: 16, marginTop: 20 },
  sectionLbl: { fontSize: 15, fontFamily: 'PlusJakartaSans_700Bold', color: '#4c1d95', marginBottom: 10 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  sectionTitle: { fontSize: 16, fontFamily: 'PlusJakartaSans_700Bold', color: '#1e1b4b' },
  sectionSub: { fontSize: 12, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(109,40,217,0.5)', marginBottom: 14 },

  stepCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#faf5ff', borderRadius: 14, padding: 12, marginBottom: 8, borderWidth: 1.5, borderColor: '#e9d5ff', gap: 10 },
  stepDone: { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' },
  stepIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#f3e8ff', alignItems: 'center', justifyContent: 'center' },
  stepIconDone: { backgroundColor: '#dcfce7' },
  stepBody: { flex: 1 },
  stepLbl: { fontSize: 13, fontFamily: 'PlusJakartaSans_700Bold', color: '#4c1d95', marginBottom: 2 },
  stepLblDone: { color: '#166534' },
  stepDesc: { fontSize: 11, fontFamily: 'PlusJakartaSans_400Regular', color: '#6b7280', lineHeight: 15 },
  stepAction: { borderRadius: 20, overflow: 'hidden' },
  stepActionBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20 },
  stepActionTxt: { fontSize: 10, fontFamily: 'PlusJakartaSans_700Bold', color: '#fff' },
  pts: { backgroundColor: '#dcfce7', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  ptsTxt: { fontSize: 11, fontFamily: 'PlusJakartaSans_700Bold', color: '#9333ea' },
  ptsTxtDone: { color: '#16a34a' },

  deliveryGrid: { flexDirection: 'row', gap: 8 },
  delivCard: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  delivInner: { padding: 14, gap: 6, alignItems: 'center', minHeight: 120, justifyContent: 'center' },
  delivInactive: { padding: 14, gap: 6, alignItems: 'center', minHeight: 120, justifyContent: 'center', backgroundColor: '#faf5ff', borderWidth: 1.5, borderColor: 'rgba(124,58,237,0.15)', borderRadius: 16 },
  delivLbl: { fontSize: 13, fontFamily: 'PlusJakartaSans_700Bold', color: '#4c1d95', textAlign: 'center' },
  delivLblActive: { color: '#fff' },
  delivSub: { fontSize: 10, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(109,40,217,0.5)', textAlign: 'center', lineHeight: 14 },
  delivSubActive: { fontSize: 10, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(255,255,255,0.8)', textAlign: 'center', lineHeight: 14 },

  legalCard: { marginHorizontal: 16, marginTop: 20, backgroundColor: '#faf5ff', borderRadius: 18, padding: 18, borderWidth: 1.5, borderColor: '#e9d5ff' },
  legalTop: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  legalIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  legalTitle: { fontSize: 16, fontFamily: 'PlusJakartaSans_700Bold', color: '#1e1b4b' },
  legalSub: { fontSize: 11, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(109,40,217,0.5)', marginTop: 2 },
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: 'rgba(124,58,237,0.3)', alignItems: 'center', justifyContent: 'center' },
  checkboxOn: { backgroundColor: '#7c3aed', borderColor: '#7c3aed' },
  checkLbl: { fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#4c1d95' },
  checkLblOn: { color: '#166534' },
  readBtn: { flexDirection: 'row', alignItems: 'center', gap: 2, backgroundColor: 'rgba(124,58,237,0.08)', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1, borderColor: 'rgba(124,58,237,0.15)' },
  readBtnTxt: { fontSize: 11, fontFamily: 'PlusJakartaSans_700Bold', color: '#7c3aed' },

  activateWrap: { marginHorizontal: 16, marginTop: 20, borderRadius: 16, overflow: 'hidden' },
  activateBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 18 },
  activateTxt: { fontSize: 16, fontFamily: 'PlusJakartaSans_700Bold', color: '#fff' },
  activateHint: { textAlign: 'center', marginTop: 10, marginHorizontal: 16, fontSize: 12, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(109,40,217,0.5)' },

  tip: { marginHorizontal: 16, marginTop: 20, backgroundColor: '#fffbeb', borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 10, borderWidth: 1, borderColor: '#fde68a' },
  tipTxt: { flex: 1, fontSize: 13, fontFamily: 'PlusJakartaSans_400Regular', color: '#78350f', lineHeight: 18 },
  tipBold: { fontFamily: 'PlusJakartaSans_700Bold', color: '#92400e' },

  // Tags
  tagCounter: { marginLeft: 'auto', backgroundColor: 'rgba(124,58,237,0.1)', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 2 },
  tagCounterTxt: { fontSize: 11, fontFamily: 'PlusJakartaSans_700Bold', color: '#7c3aed' },
  tagsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, paddingVertical: 7, borderRadius: 50, backgroundColor: 'rgba(124,58,237,0.07)', borderWidth: 1.5, borderColor: 'rgba(124,58,237,0.18)' },
  tagChipActive: { backgroundColor: '#7c3aed', borderColor: '#7c3aed' },
  tagChipDisabled: { borderColor: 'rgba(124,58,237,0.08)' },
  tagChipTxt: { fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#4c1d95' },
  tagChipTxtActive: { color: '#fff' },
  tagsSelectedRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12, minHeight: 32 },
  tagSelected: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#7c3aed', borderRadius: 50, paddingHorizontal: 12, paddingVertical: 6 },
  tagSelectedTxt: { fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#fff' },
  tagsEmptyHint: { fontSize: 12, fontFamily: 'PlusJakartaSans_400Regular', color: 'rgba(109,40,217,0.4)', fontStyle: 'italic', paddingVertical: 4 },
  tagsSuggestBox: { backgroundColor: 'rgba(124,58,237,0.05)', borderRadius: 14, padding: 12, borderWidth: 1, borderColor: 'rgba(124,58,237,0.1)' },
  tagsSuggestLbl: { fontSize: 11, fontFamily: 'PlusJakartaSans_600SemiBold', color: 'rgba(109,40,217,0.5)', marginBottom: 10, letterSpacing: 0.3 },
  tagsSuggestRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagSuggest: { backgroundColor: 'rgba(124,58,237,0.08)', borderRadius: 50, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: 'rgba(124,58,237,0.18)' },
  tagSuggestTxt: { fontSize: 12, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#7c3aed' },
  tagInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  tagInput: { flex: 1, backgroundColor: '#fff', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 13, fontFamily: 'PlusJakartaSans_400Regular', color: '#1e1b4b', borderWidth: 1.5, borderColor: 'rgba(124,58,237,0.2)' },
  tagInputBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#7c3aed', alignItems: 'center', justifyContent: 'center' },
  tagInputBtnDisabled: { backgroundColor: 'rgba(124,58,237,0.25)' },
  tagSaveBtn: { marginTop: 14, borderRadius: 14, overflow: 'hidden' },
  tagSaveBtnInner: { paddingVertical: 13, paddingHorizontal: 20, alignItems: 'center' },
  tagSaveTxt: { fontSize: 14, fontFamily: 'PlusJakartaSans_700Bold', color: '#fff' },

  // Stripe card (visible in main scroll)
  stripeCard: { marginHorizontal: 16, marginBottom: 16, borderRadius: 18, backgroundColor: '#f8f7ff', borderWidth: 1, borderColor: '#e0d9ff', padding: 16 },
  stripeHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 14 },
  stripeIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stripeTitle: { fontSize: 15, fontFamily: 'PlusJakartaSans_700Bold', color: '#1e1b4b', marginBottom: 2 },
  stripeSub: { fontSize: 12, fontFamily: 'PlusJakartaSans_400Regular', color: '#6b7280', lineHeight: 17 },
  stripeManageBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#faf5ff', alignItems: 'center', justifyContent: 'center' },
  stripeConnected: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#f0fdf4', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#bbf7d0' },
  stripeConnectedTxt: { flex: 1, fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#166534' },
  stripeBadges: { flexDirection: 'row', gap: 6 },
  stripeBadge: { backgroundColor: '#dcfce7', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  stripeBadgeTxt: { fontSize: 10, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#16a34a' },
  stripePending: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#fffbeb', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#fde68a' },
  stripePendingTxt: { flex: 1, fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#92400e' },
  stripeRestricted: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#fef2f2', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#fecaca' },
  stripeRestrictedTxt: { flex: 1, fontSize: 13, fontFamily: 'PlusJakartaSans_600SemiBold', color: '#991b1b' },
  stripeBadgeWarning: { backgroundColor: '#fef3c7', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  stripeBadgeError: { backgroundColor: '#fee2e2', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  stripeConnectBtn: { borderRadius: 14, overflow: 'hidden' },
  stripeConnectBtnInner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14 },
  stripeConnectTxt: { fontSize: 14, fontFamily: 'PlusJakartaSans_700Bold', color: '#fff' },
});
